// src/app/features/clinics/clinics.component.ts
import { Component, Output, EventEmitter, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LanguageService } from '../../core/services/language.service';
import { DataService } from '../../core/services/data.service';

@Component({
  selector: 'app-clinics',
  standalone: true,
  imports: [CommonModule],
  template: `
    <section style="background-color: var(--primary-light); padding: 3.5rem 0;">
      <div className="container" style="text-align: center; max-width: 800px;">
        <span className="section-subtitle">{{ lang.ui().clinics }}</span>
        <h1 className="section-title">{{ lang.isRtl() ? 'مواقع العيادات ومواعيد العمل' : 'Clinic Locations & Schedules' }}</h1>
      </div>
    </section>

    <section style="padding: 5rem 0;">
      <div className="container">
        <div style="display: flex; flex-direction: column; gap: 2.5rem;">
          <div *ngFor="let clinic of data.getClinics()" className="card" style="padding: 2.5rem; display: grid; grid-template-columns: 1fr 1fr; gap: 2.5rem;" class="grid-responsive">
            <div>
              <span style="background-color: var(--accent-teal-light); color: var(--accent-teal); padding: 0.3rem 0.85rem; border-radius: var(--radius-full); font-weight: 700; font-size: 0.85rem; display: inline-block; margin-bottom: 1rem;">
                {{ lang.getText(clinic.city) }}
              </span>

              <h2 style="font-size: 1.6rem; color: var(--primary-dark); font-weight: 800; margin-bottom: 1rem;">
                {{ lang.getText(clinic.name) }}
              </h2>

              <p style="font-size: 1rem; color: var(--text-main); line-height: 1.6; margin-bottom: 1.25rem;">
                <strong>{{ lang.isRtl() ? 'العنوان تفصيلاً:' : 'Address:' }}</strong> {{ lang.getText(clinic.address) }}
              </p>

              <p style="font-size: 1.1rem; color: var(--primary-dark); font-weight: 700; margin-bottom: 1.5rem;">
                {{ lang.isRtl() ? 'رقم الهاتف والواتساب:' : 'Phone & WhatsApp:' }} <span style="color: var(--accent-teal);">{{ clinic.phone }}</span>
              </p>

              <button (click)="nav('appointments')" className="btn btn-primary btn-lg">
                <span>{{ lang.ui().bookAppointment }}</span>
              </button>
            </div>

            <div style="background-color: var(--bg-alt); padding: 1.75rem; border-radius: var(--radius-md); border: 1px solid var(--border-light);">
              <h4 style="font-size: 1.15rem; color: var(--primary-dark); font-weight: 800; margin-bottom: 1rem;">
                {{ lang.isRtl() ? 'مواعيد العمل:' : 'Working Hours:' }}
              </h4>

              <ul style="list-style: none; display: flex; flex-direction: column; gap: 0.75rem; padding: 0; margin-bottom: 1.5rem;">
                <li *ngFor="let wh of clinic.workingHours" style="font-size: 0.95rem; color: var(--text-main); font-weight: 600; display: flex; align-items: center; gap: 0.5rem;">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="var(--accent-teal)" stroke-width="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
                  <span>{{ lang.getText(wh) }}</span>
                </li>
              </ul>

              <h4 style="font-size: 1.1rem; color: var(--primary-dark); font-weight: 800; margin-bottom: 0.75rem;">
                {{ lang.isRtl() ? 'الخدمات المتاحة بالفرع:' : 'Services Available:' }}
              </h4>

              <div style="display: flex; flex-direction: column; gap: 0.5rem;">
                <div *ngFor="let srv of clinic.services" style="font-size: 0.9rem; color: var(--text-muted); display: flex; align-items: center; gap: 0.5rem;">
                  <span style="color: var(--accent-teal);">•</span>
                  <span>{{ lang.getText(srv.name) }}</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <style>
      @media (max-width: 992px) {
        .grid-responsive { grid-template-columns: 1fr !important; }
      }
    </style>
  `
})
export class ClinicsComponent {
  lang = inject(LanguageService);
  data = inject(DataService);

  @Output() tabChange = new EventEmitter<string>();

  nav(tab: string): void {
    this.tabChange.emit(tab);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}

// src/pages/Clinics.tsx
import React from 'react';
import { useLanguage } from '../context/LanguageContext';
import { dataService } from '../services/dataService';
import { MapPin, Phone, Clock, Calendar, Navigation, CheckCircle2, ShieldCheck } from 'lucide-react';

interface ClinicsProps {
  setActiveTab: (tab: string) => void;
  onSelectClinic?: (clinicId: string) => void;
}

export const Clinics: React.FC<ClinicsProps> = ({ setActiveTab, onSelectClinic }) => {
  const { isRtl, getText, ui } = useLanguage();
  const clinics = dataService.getClinics();

  const handleBookClinic = (clinicId: string) => {
    if (onSelectClinic) onSelectClinic(clinicId);
    setActiveTab('appointments');
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  return (
    <div>
      {/* Hero Header */}
      <section style={{ backgroundColor: 'var(--primary-light)', padding: '4rem 0' }}>
        <div className="container" style={{ textAlign: 'center', maxWidth: '800px' }}>
          <span className="section-subtitle">{isRtl ? 'مواقع العيادات والرعاية' : 'Practices & Locations'}</span>
          <h1 style={{ color: 'var(--primary-dark)', marginBottom: '1rem' }}>
            {isRtl ? 'عناوين ومواعيد العيادات' : 'Clinic Locations & Schedules'}
          </h1>
          <p style={{ fontSize: '1.1rem', color: 'var(--text-muted)' }}>
            {isRtl
              ? 'اختر الفرع والمدينة الأنسب لك واستكشف مواعيد العمل والخدمات المتاحة.'
              : 'Choose the location that works best for you and book your consultation.'}
          </p>
        </div>
      </section>

      {/* Clinics Detail Section */}
      <section className="section">
        <div className="container">
          <div style={{ display: 'flex', flexDirection: 'column', gap: '3rem' }}>
            {clinics.map(clinic => (
              <div key={clinic.id} className="card" style={{ padding: '2.5rem', backgroundColor: '#ffffff' }}>
                <div style={{ display: 'flex', gap: '2.5rem', flexWrap: 'wrap' }}>
                  {/* Left Clinic Info */}
                  <div style={{ flex: '1 1 450px' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', marginBottom: '1rem' }}>
                      <span className="badge badge-navy">
                        <MapPin size={14} /> {getText(clinic.city)}
                      </span>
                      <span className="badge badge-teal">
                        <ShieldCheck size={14} /> {isRtl ? 'عيادة معتمدة' : 'Verified Clinic'}
                      </span>
                    </div>

                    <h2 style={{ fontSize: '2rem', color: 'var(--primary-dark)', marginBottom: '0.75rem' }}>
                      {getText(clinic.name)}
                    </h2>

                    <p style={{ fontSize: '1.05rem', color: 'var(--text-muted)', marginBottom: '1.5rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      <MapPin size={18} color="var(--accent-teal)" />
                      <span>{getText(clinic.address)}</span>
                    </p>

                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.6rem', fontSize: '1.05rem', fontWeight: 700, color: 'var(--primary-navy)', marginBottom: '2rem' }}>
                      <Phone size={18} color="var(--accent-teal)" />
                      <span>{clinic.phone}</span>
                    </div>

                    {/* Working Hours */}
                    <div style={{ backgroundColor: 'var(--bg-alt)', borderRadius: 'var(--radius-md)', padding: '1.25rem', marginBottom: '2rem' }}>
                      <h4 style={{ color: 'var(--primary-dark)', marginBottom: '0.75rem', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                        <Clock size={18} color="var(--accent-teal)" />
                        <span>{isRtl ? 'جدول ومواعيد العيادة:' : 'Working Hours Schedule:'}</span>
                      </h4>
                      <ul style={{ listStyle: 'none', display: 'flex', flexDirection: 'column', gap: '0.4rem' }}>
                        {clinic.workingHours.map((wh, idx) => (
                          <li key={idx} style={{ fontSize: '0.95rem', color: 'var(--text-main)', fontWeight: 600 }}>
                            • {getText(wh)}
                          </li>
                        ))}
                      </ul>
                    </div>

                    {/* Available Services Tags */}
                    <div style={{ marginBottom: '2rem' }}>
                      <h4 style={{ fontSize: '0.95rem', color: 'var(--primary-dark)', marginBottom: '0.75rem' }}>
                        {isRtl ? 'الخدمات الطبية المتاحة:' : 'Available Medical Services:'}
                      </h4>
                      <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                        {clinic.services.map(srv => (
                          <span key={srv.id} style={{ display: 'inline-flex', alignItems: 'center', gap: '0.35rem', backgroundColor: 'var(--accent-teal-light)', color: 'var(--accent-teal-hover)', padding: '0.35rem 0.75rem', borderRadius: 'var(--radius-full)', fontSize: '0.85rem', fontWeight: 600 }}>
                            <CheckCircle2 size={14} />
                            {getText(srv.name)}
                          </span>
                        ))}
                      </div>
                    </div>

                    {/* Action Buttons */}
                    <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
                      <button
                        onClick={() => handleBookClinic(clinic.id)}
                        className="btn btn-primary"
                      >
                        <Calendar size={18} />
                        <span>{ui.bookAppointment}</span>
                      </button>

                      {clinic.mapLocationUrl && (
                        <a
                          href={clinic.mapLocationUrl}
                          target="_blank"
                          rel="noopener noreferrer"
                          className="btn btn-outline"
                        >
                          <Navigation size={18} />
                          <span>{ui.getDirections}</span>
                        </a>
                      )}
                    </div>
                  </div>

                  {/* Right Map Embed View */}
                  <div style={{ flex: '1 1 350px', minHeight: '300px', borderRadius: 'var(--radius-lg)', overflow: 'hidden', border: '1px solid var(--border-light)' }}>
                    <iframe
                      title={getText(clinic.name)}
                      src={clinic.googleMapsEmbedUrl}
                      width="100%"
                      height="100%"
                      style={{ border: 0, minHeight: '320px' }}
                      allowFullScreen
                      loading="lazy"
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
};
