// frontend/src/pages/Contact.tsx
import React, { useState } from 'react';
import { useLanguage } from '../context/LanguageContext';
import { dataService } from '../services/dataService';
import { Phone, Mail, MessageSquare, Send, CheckCircle } from 'lucide-react';

interface ContactProps {
  setActiveTab: (tab: string) => void;
}

export const Contact: React.FC<ContactProps> = ({ setActiveTab }) => {
  const { isRtl, getText, ui } = useLanguage();
  const settings = dataService.getSettings();
  const clinics = dataService.getClinics();

  // Contact Form State
  const [fullName, setFullName] = useState('');
  const [email, setEmail] = useState('');
  const [phone, setPhone] = useState('');
  const [subject, setSubject] = useState('');
  const [message, setMessage] = useState('');
  const [submitted, setSubmitted] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!fullName || !email || !message) return;

    dataService.addMessage({
      fullName,
      email,
      phone,
      subject,
      message
    });

    setSubmitted(true);
    setFullName('');
    setEmail('');
    setPhone('');
    setSubject('');
    setMessage('');
  };

  return (
    <div>
      {/* Hero Header */}
      <section style={{ backgroundColor: 'var(--primary-light)', padding: '4rem 0' }}>
        <div className="container" style={{ textAlign: 'center', maxWidth: '800px' }}>
          <span className="section-subtitle">{isRtl ? 'التواصل المباشر' : 'Direct Inquiry'}</span>
          <h1 style={{ color: 'var(--primary-dark)', marginBottom: '1rem' }}>
            {isRtl ? 'تواصل معنا' : 'Get in Touch'}
          </h1>
          <p style={{ fontSize: '1.1rem', color: 'var(--text-muted)' }}>
            "{isRtl
              ? 'للحجوزات، أو استفسارات العيادات، أو الاستشارات المهنية والأكاديمية، يسعدنا تواصلكم عبر الخيارات أدناه.'
              : 'For appointments, clinic information, or professional inquiries, please use the appropriate contact option below.'}"
          </p>
        </div>
      </section>

      {/* Main Contact Section */}
      <section className="section">
        <div className="container">
          <div style={{ display: 'flex', gap: '3rem', flexWrap: 'wrap' }}>
            {/* Left Contact Cards */}
            <div style={{ flex: '1 1 350px' }}>
              <h2 style={{ fontSize: '1.6rem', marginBottom: '1.5rem', color: 'var(--primary-dark)' }}>
                {isRtl ? 'معلومات التواصل' : 'Contact Information'}
              </h2>

              <div style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem', marginBottom: '2.5rem' }}>
                <div className="card" style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                  <div style={{ width: '42px', height: '42px', borderRadius: '10px', backgroundColor: 'var(--accent-teal-light)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <Phone size={22} color="var(--accent-teal)" />
                  </div>
                  <div>
                    <div style={{ fontSize: '0.825rem', color: 'var(--text-light)', fontWeight: 600 }}>{isRtl ? 'الهاتف المباشر' : 'Phone Number'}</div>
                    <div style={{ fontSize: '1.05rem', fontWeight: 700, color: 'var(--primary-dark)' }}>{settings.contactPhone}</div>
                  </div>
                </div>

                <div className="card" style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
                  <div style={{ width: '42px', height: '42px', borderRadius: '10px', backgroundColor: 'var(--accent-teal-light)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <Mail size={22} color="var(--accent-teal)" />
                  </div>
                  <div>
                    <div style={{ fontSize: '0.825rem', color: 'var(--text-light)', fontWeight: 600 }}>{isRtl ? 'البريد الإلكتروني' : 'Email Address'}</div>
                    <div style={{ fontSize: '1.05rem', fontWeight: 700, color: 'var(--primary-dark)' }}>{settings.contactEmail}</div>
                  </div>
                </div>

                <a
                  href={`https://wa.me/${settings.whatsappNumber}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="card card-hover"
                  style={{ display: 'flex', alignItems: 'center', gap: '1rem', borderLeft: '4px solid #25D366' }}
                >
                  <div style={{ width: '42px', height: '42px', borderRadius: '10px', backgroundColor: '#DCF8C6', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
                    <MessageSquare size={22} color="#075E54" />
                  </div>
                  <div>
                    <div style={{ fontSize: '0.825rem', color: 'var(--text-light)', fontWeight: 600 }}>WhatsApp Chat</div>
                    <div style={{ fontSize: '1.05rem', fontWeight: 700, color: '#075E54' }}>{settings.whatsappNumber}</div>
                  </div>
                </a>
              </div>

              {/* Clinic Summaries */}
              <h3 style={{ fontSize: '1.25rem', marginBottom: '1rem', color: 'var(--primary-dark)' }}>
                {ui.clinicLocations}
              </h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '1rem' }}>
                {clinics.map(clinic => (
                  <div key={clinic.id} style={{ backgroundColor: 'var(--bg-alt)', padding: '1rem 1.25rem', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-light)' }}>
                    <div style={{ fontWeight: 700, color: 'var(--primary-dark)', fontSize: '1rem', marginBottom: '0.25rem' }}>
                      {getText(clinic.name)} ({getText(clinic.city)})
                    </div>
                    <div style={{ fontSize: '0.88rem', color: 'var(--text-muted)', marginBottom: '0.5rem' }}>
                      {getText(clinic.address)}
                    </div>
                    <button
                      onClick={() => setActiveTab('appointments')}
                      className="btn btn-outline btn-sm"
                      style={{ fontSize: '0.8rem', padding: '0.3rem 0.75rem' }}
                    >
                      {ui.bookAppointment}
                    </button>
                  </div>
                ))}
              </div>
            </div>

            {/* Right Contact Form */}
            <div style={{ flex: '1 1 450px' }}>
              <div className="card" style={{ backgroundColor: '#ffffff', padding: '2.25rem' }}>
                <h2 style={{ fontSize: '1.6rem', marginBottom: '1.5rem', color: 'var(--primary-dark)' }}>
                  {isRtl ? 'إرسال رسالة مباشرة' : 'Send a Direct Message'}
                </h2>

                {submitted ? (
                  <div style={{ textAlign: 'center', padding: '2rem 1rem' }}>
                    <CheckCircle size={48} color="var(--accent-teal)" style={{ marginBottom: '1rem' }} />
                    <h3 style={{ color: 'var(--primary-dark)', marginBottom: '0.5rem' }}>
                      {isRtl ? 'تم إرسال رسالتك بنجاح!' : 'Message Sent Successfully!'}
                    </h3>
                    <p style={{ color: 'var(--text-muted)', marginBottom: '1.5rem' }}>
                      {isRtl ? 'سيقوم فريق العيادة بالرد على استفسارك في أقرب وقت.' : 'Our clinic reception will review your message and reply promptly.'}
                    </p>
                    <button onClick={() => setSubmitted(false)} className="btn btn-outline btn-sm">
                      {isRtl ? 'إرسال رسالة أخرى' : 'Send Another Message'}
                    </button>
                  </div>
                ) : (
                  <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
                    <div>
                      <label style={{ display: 'block', fontWeight: 700, fontSize: '0.9rem', marginBottom: '0.35rem' }}>
                        {isRtl ? 'الاسم الكامل *' : 'Full Name *'}
                      </label>
                      <input
                        type="text"
                        required
                        value={fullName}
                        onChange={e => setFullName(e.target.value)}
                        placeholder={isRtl ? 'أدخل اسمك' : 'Your full name'}
                        style={{
                          width: '100%',
                          padding: '0.75rem 1rem',
                          borderRadius: 'var(--radius-md)',
                          border: '1px solid var(--border-light)',
                          fontSize: '0.95rem',
                          outline: 'none'
                        }}
                      />
                    </div>

                    <div className="grid-2" style={{ gap: '1rem' }}>
                      <div>
                        <label style={{ display: 'block', fontWeight: 700, fontSize: '0.9rem', marginBottom: '0.35rem' }}>
                          {isRtl ? 'البريد الإلكتروني *' : 'Email *'}
                        </label>
                        <input
                          type="email"
                          required
                          value={email}
                          onChange={e => setEmail(e.target.value)}
                          placeholder="email@example.com"
                          style={{
                            width: '100%',
                            padding: '0.75rem 1rem',
                            borderRadius: 'var(--radius-md)',
                            border: '1px solid var(--border-light)',
                            fontSize: '0.95rem',
                            outline: 'none'
                          }}
                        />
                      </div>

                      <div>
                        <label style={{ display: 'block', fontWeight: 700, fontSize: '0.9rem', marginBottom: '0.35rem' }}>
                          {isRtl ? 'رقم الهاتف' : 'Phone Number'}
                        </label>
                        <input
                          type="tel"
                          value={phone}
                          onChange={e => setPhone(e.target.value)}
                          placeholder="+20 100 000 0000"
                          style={{
                            width: '100%',
                            padding: '0.75rem 1rem',
                            borderRadius: 'var(--radius-md)',
                            border: '1px solid var(--border-light)',
                            fontSize: '0.95rem',
                            outline: 'none'
                          }}
                        />
                      </div>
                    </div>

                    <div>
                      <label style={{ display: 'block', fontWeight: 700, fontSize: '0.9rem', marginBottom: '0.35rem' }}>
                        {isRtl ? 'الموضوع' : 'Subject'}
                      </label>
                      <input
                        type="text"
                        value={subject}
                        onChange={e => setSubject(e.target.value)}
                        placeholder={isRtl ? 'موضوع الرسالة...' : 'Inquiry subject'}
                        style={{
                          width: '100%',
                          padding: '0.75rem 1rem',
                          borderRadius: 'var(--radius-md)',
                          border: '1px solid var(--border-light)',
                          fontSize: '0.95rem',
                          outline: 'none'
                        }}
                      />
                    </div>

                    <div>
                      <label style={{ display: 'block', fontWeight: 700, fontSize: '0.9rem', marginBottom: '0.35rem' }}>
                        {isRtl ? 'الرسالة *' : 'Message *'}
                      </label>
                      <textarea
                        rows={4}
                        required
                        value={message}
                        onChange={e => setMessage(e.target.value)}
                        placeholder={isRtl ? 'اكتب نص استفسارك هنا...' : 'Write your message details...'}
                        style={{
                          width: '100%',
                          padding: '0.75rem 1rem',
                          borderRadius: 'var(--radius-md)',
                          border: '1px solid var(--border-light)',
                          fontSize: '0.95rem',
                          outline: 'none'
                        }}
                      />
                    </div>

                    <button type="submit" className="btn btn-primary" style={{ justifyContent: 'center' }}>
                      <Send size={18} />
                      <span>{ui.sendMessage}</span>
                    </button>
                  </form>
                )}
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

// frontend/src/app/features/contact/contact.component.ts
import { Component, Output, EventEmitter, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LanguageService } from '../../core/services/language.service';
import { DataService } from '../../core/services/data.service';
import { ApiService } from '../../core/services/api.service';

@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div>
      <!-- Hero Header -->
      <section style="background-color: var(--primary-light); padding: 4rem 0;">
        <div class="container" style="text-align: center; max-width: 800px;">
          <span class="section-subtitle">{{ lang.isRtl() ? 'تواصل معنا' : 'Get in Touch' }}</span>
          <h1 style="color: var(--primary-dark); margin-bottom: 1rem;">
            {{ lang.isRtl() ? 'التواصل المباشر والاستفسارات' : 'Contact Dr. Ibrahim El Sherqawy' }}
          </h1>
          <p style="font-size: 1.1rem; color: var(--text-muted);">
            {{ lang.isRtl()
              ? 'يسعدنا استقبال استفساراتكم وحجوزاتكم عبر النموذج المباشر أو أرقام العيادة.'
              : 'Reach out for consultation inquiries, academic collaborations, or appointment bookings.' }}
          </p>
        </div>
      </section>

      <!-- Main Contact Section -->
      <section class="section">
        <div class="container">
          <div style="display: flex; gap: 3.5rem; flex-wrap: wrap;">
            <!-- Left Info Column -->
            <div style="flex: 1 1 400px;">
              <h2 style="font-size: 1.8rem; margin-bottom: 1.5rem; color: var(--primary-dark);">
                {{ lang.isRtl() ? 'معلومات الاتصال المباشرة' : 'Direct Contact Info' }}
              </h2>

              <div style="display: flex; flex-direction: column; gap: 1.25rem; margin-bottom: 2.5rem;">
                <div style="display: flex; align-items: center; gap: 1rem; padding: 1.25rem; background-color: var(--accent-teal-light); border-radius: var(--radius-md);">
                  <div style="width: 44px; height: 44px; border-radius: 50%; background-color: #ffffff; display: flex; align-items: center; justify-content: center;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="var(--accent-teal)" stroke-width="2"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>
                  </div>
                  <div>
                    <div style="font-size: 0.85rem; color: var(--text-muted); font-weight: 600;">
                      {{ lang.isRtl() ? 'هاتف العيادات الموحد' : 'Central Clinic Phone' }}
                    </div>
                    <div style="font-size: 1.1rem; font-weight: 800; color: var(--primary-dark);">
                      01000577622
                    </div>
                  </div>
                </div>

                <div style="display: flex; align-items: center; gap: 1rem; padding: 1.25rem; background-color: var(--primary-light); border-radius: var(--radius-md);">
                  <div style="width: 44px; height: 44px; border-radius: 50%; background-color: #ffffff; display: flex; align-items: center; justify-content: center;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="var(--primary-navy)" stroke-width="2"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>
                  </div>
                  <div>
                    <div style="font-size: 0.85rem; color: var(--text-muted); font-weight: 600;">
                      {{ lang.isRtl() ? 'البريد الإلكتروني الرسمي' : 'Official Email' }}
                    </div>
                    <div style="font-size: 1.05rem; font-weight: 800; color: var(--primary-dark);">
                      info&#64;drelsharkawy.com
                    </div>
                  </div>
                </div>
              </div>

              <!-- Clinic Summaries -->
              <h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--primary-dark);">
                {{ lang.ui().clinicLocations }}
              </h3>
              <div style="display: flex; flex-direction: column; gap: 1rem;">
                <div *ngFor="let clinic of data.getClinics()" style="background-color: var(--bg-alt); padding: 1rem 1.25rem; border-radius: var(--radius-md); border: 1px solid var(--border-light);">
                  <div style="font-weight: 700; color: var(--primary-dark); font-size: 1rem; margin-bottom: 0.25rem;">
                    {{ lang.getText(clinic.name) }} ({{ lang.getText(clinic.city) }})
                  </div>
                  <div style="font-size: 0.88rem; color: var(--text-muted); margin-bottom: 0.5rem;">
                    {{ lang.getText(clinic.address) }}
                  </div>
                  <button (click)="nav('appointments')" class="btn btn-outline btn-sm" style="font-size: 0.8rem; padding: 0.3rem 0.75rem;">
                    {{ lang.ui().bookAppointment }}
                  </button>
                </div>
              </div>
            </div>

            <!-- Right Contact Form -->
            <div style="flex: 1 1 450px;">
              <div class="card" style="background-color: #ffffff; padding: 2.25rem;">
                <h2 style="font-size: 1.6rem; margin-bottom: 1.5rem; color: var(--primary-dark);">
                  {{ lang.isRtl() ? 'إرسال رسالة مباشرة' : 'Send a Direct Message' }}
                </h2>

                <div *ngIf="submitted" style="text-align: center; padding: 2rem 1rem;">
                  <svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="var(--accent-teal)" stroke-width="2" style="margin-bottom: 1rem;"><path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/></svg>
                  <h3 style="color: var(--primary-dark); margin-bottom: 0.5rem;">
                    {{ lang.isRtl() ? 'تم إرسال رسالتك بنجاح!' : 'Message Sent Successfully!' }}
                  </h3>
                  <p style="color: var(--text-muted); margin-bottom: 1.5rem;">
                    {{ lang.isRtl() ? 'سيقوم فريق العيادة بالرد على استفسارك في أقرب وقت.' : 'Our clinic reception will review your message and reply promptly.' }}
                  </p>
                  <button (click)="submitted = false" class="btn btn-outline btn-sm">
                    {{ lang.isRtl() ? 'إرسال رسالة أخرى' : 'Send Another Message' }}
                  </button>
                </div>

                <form *ngIf="!submitted" (ngSubmit)="handleSubmit()" style="display: flex; flex-direction: column; gap: 1.25rem;">
                  <div>
                    <label style="display: block; font-weight: 700; font-size: 0.9rem; margin-bottom: 0.35rem;">
                      {{ lang.isRtl() ? 'الاسم الكامل *' : 'Full Name *' }}
                    </label>
                    <input type="text" required [(ngModel)]="fullName" name="fullName" class="input-field" [placeholder]="lang.isRtl() ? 'أدخل اسمك' : 'Your full name'" />
                  </div>

                  <div class="grid-2" style="gap: 1rem;">
                    <div>
                      <label style="display: block; font-weight: 700; font-size: 0.9rem; margin-bottom: 0.35rem;">
                        {{ lang.isRtl() ? 'البريد الإلكتروني *' : 'Email *' }}
                      </label>
                      <input type="email" required [(ngModel)]="email" name="email" class="input-field" placeholder="email@example.com" />
                    </div>

                    <div>
                      <label style="display: block; font-weight: 700; font-size: 0.9rem; margin-bottom: 0.35rem;">
                        {{ lang.isRtl() ? 'رقم الهاتف' : 'Phone Number' }}
                      </label>
                      <input type="tel" [(ngModel)]="phone" name="phone" class="input-field" placeholder="01000000000" />
                    </div>
                  </div>

                  <div>
                    <label style="display: block; font-weight: 700; font-size: 0.9rem; margin-bottom: 0.35rem;">
                      {{ lang.isRtl() ? 'الموضوع' : 'Subject' }}
                    </label>
                    <input type="text" [(ngModel)]="subject" name="subject" class="input-field" [placeholder]="lang.isRtl() ? 'موضوع الرسالة...' : 'Inquiry subject'" />
                  </div>

                  <div>
                    <label style="display: block; font-weight: 700; font-size: 0.9rem; margin-bottom: 0.35rem;">
                      {{ lang.isRtl() ? 'الرسالة *' : 'Message *' }}
                    </label>
                    <textarea rows="4" required [(ngModel)]="message" name="message" class="input-field" [placeholder]="lang.isRtl() ? 'اكتب نص استفسارك هنا...' : 'Write your message details...'"></textarea>
                  </div>

                  <button type="submit" class="btn btn-primary" style="justify-content: center;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="22" x2="11" y1="2" y2="13"/><polygon points="22 2 15 22 11 13 2 9 22 2"/></svg>
                    <span>{{ lang.ui().sendMessage }}</span>
                  </button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  `
})
export class ContactComponent {
  lang = inject(LanguageService);
  data = inject(DataService);
  api = inject(ApiService);

  @Output() tabChange = new EventEmitter<string>();

  fullName = '';
  email = '';
  phone = '';
  subject = '';
  message = '';
  submitted = false;

  nav(tab: string): void {
    this.tabChange.emit(tab);
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  handleSubmit(): void {
    if (!this.fullName || !this.email || !this.message) return;

    this.api.sendMessage({
      fullName: this.fullName,
      email: this.email,
      phone: this.phone,
      subject: this.subject,
      message: this.message
    }).subscribe({
      next: () => {
        this.submitted = true;
      },
      error: () => {
        this.submitted = true;
      }
    });
  }
}
