// frontend/src/pages/Publications.tsx
import React, { useState, useMemo } from 'react';
import { useLanguage } from '../context/LanguageContext';
import { dataService } from '../services/dataService';
import type { PublicationItem } from '../types';
import { BookOpen, Search, ExternalLink, X } from 'lucide-react';

export const Publications: React.FC = () => {
  const { isRtl, getText, ui } = useLanguage();
  const publications = dataService.getPublications();

  const [searchTerm, setSearchTerm] = useState('');
  const [selectedYear, setSelectedYear] = useState<string>('ALL');
  const [selectedType, setSelectedType] = useState<string>('ALL');
  const [selectedPub, setSelectedPub] = useState<PublicationItem | null>(null);

  // Extract unique years & types
  const years = useMemo(() => {
    const set = new Set(publications.map(p => p.year));
    return Array.from(set).sort((a, b) => b - a);
  }, [publications]);

  const types = useMemo(() => {
    const set = new Set(publications.map(p => p.type));
    return Array.from(set);
  }, [publications]);

  // Filter logic
  const filteredPubs = useMemo(() => {
    return publications.filter(pub => {
      const titleStr = getText(pub.title).toLowerCase();
      const authorStr = pub.authors.toLowerCase();
      const journalStr = pub.journal.toLowerCase();
      const keywordStr = pub.keywords.join(' ').toLowerCase();
      const query = searchTerm.toLowerCase();

      const matchesSearch = !query || titleStr.includes(query) || authorStr.includes(query) || journalStr.includes(query) || keywordStr.includes(query);
      const matchesYear = selectedYear === 'ALL' || pub.year.toString() === selectedYear;
      const matchesType = selectedType === 'ALL' || pub.type === selectedType;

      return matchesSearch && matchesYear && matchesType;
    });
  }, [publications, searchTerm, selectedYear, selectedType, getText]);

  return (
    <div>
      {/* Hero Header */}
      <section style={{ backgroundColor: 'var(--primary-light)', padding: '4rem 0' }}>
        <div className="container" style={{ textAlign: 'center', maxWidth: '800px' }}>
          <span className="section-subtitle">{isRtl ? 'المكتبة الأكاديمية' : 'Academic Library'}</span>
          <h1 style={{ color: 'var(--primary-dark)', marginBottom: '1rem' }}>
            {isRtl ? 'الأبحاث والمنشورات العلمية' : 'Scientific Publications'}
          </h1>
          <p style={{ fontSize: '1.1rem', color: 'var(--text-muted)' }}>
            {isRtl
              ? 'مكتبة تفاعلية قابلة للبحث تضم الأبحاث والمراجعات العلمية المنشورة في الدوريات العالمية.'
              : 'Explore peer-reviewed original research, clinical trials, and review articles.'}
          </p>
        </div>
      </section>

      {/* Search & Filter Bar */}
      <section className="section" style={{ paddingTop: '2.5rem', paddingBottom: '1.5rem' }}>
        <div className="container">
          <div
            className="card"
            style={{
              backgroundColor: 'var(--bg-alt)',
              padding: '1.5rem',
              display: 'flex',
              gap: '1rem',
              flexWrap: 'wrap',
              alignItems: 'center'
            }}
          >
            {/* Search Input */}
            <div style={{ flex: '2 1 300px', position: 'relative' }}>
              <Search
                size={18}
                color="var(--text-light)"
                style={{ position: 'absolute', top: '50%', transform: 'translateY(-50%)', [isRtl ? 'right' : 'left']: '1rem' }}
              />
              <input
                type="text"
                placeholder={ui.search}
                value={searchTerm}
                onChange={e => setSearchTerm(e.target.value)}
                style={{
                  width: '100%',
                  padding: '0.75rem 1rem',
                  paddingLeft: isRtl ? '1rem' : '2.5rem',
                  paddingRight: isRtl ? '2.5rem' : '1rem',
                  borderRadius: 'var(--radius-md)',
                  border: '1px solid var(--border-light)',
                  fontSize: '0.95rem',
                  outline: 'none'
                }}
              />
            </div>

            {/* Year Filter */}
            <div style={{ flex: '1 1 160px' }}>
              <select
                value={selectedYear}
                onChange={e => setSelectedYear(e.target.value)}
                style={{
                  width: '100%',
                  padding: '0.75rem 1rem',
                  borderRadius: 'var(--radius-md)',
                  border: '1px solid var(--border-light)',
                  fontSize: '0.92rem',
                  backgroundColor: '#ffffff',
                  outline: 'none'
                }}
              >
                <option value="ALL">{ui.filterByYear} (All)</option>
                {years.map(y => (
                  <option key={y} value={y}>{y}</option>
                ))}
              </select>
            </div>

            {/* Type Filter */}
            <div style={{ flex: '1 1 180px' }}>
              <select
                value={selectedType}
                onChange={e => setSelectedType(e.target.value)}
                style={{
                  width: '100%',
                  padding: '0.75rem 1rem',
                  borderRadius: 'var(--radius-md)',
                  border: '1px solid var(--border-light)',
                  fontSize: '0.92rem',
                  backgroundColor: '#ffffff',
                  outline: 'none'
                }}
              >
                <option value="ALL">{ui.allTypes}</option>
                {types.map(t => (
                  <option key={t} value={t}>{t}</option>
                ))}
              </select>
            </div>

            {/* Clear Button */}
            {(searchTerm || selectedYear !== 'ALL' || selectedType !== 'ALL') && (
              <button
                onClick={() => {
                  setSearchTerm('');
                  setSelectedYear('ALL');
                  setSelectedType('ALL');
                }}
                className="btn btn-outline btn-sm"
              >
                {ui.clearFilters}
              </button>
            )}
          </div>
        </div>
      </section>

      {/* Publications List */}
      <section className="section" style={{ paddingTop: '1rem' }}>
        <div className="container">
          <div style={{ fontSize: '0.9rem', color: 'var(--text-muted)', marginBottom: '1.5rem' }}>
            {isRtl ? `تم العثور على ${filteredPubs.length} بحث علمي` : `Showing ${filteredPubs.length} research publications`}
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
            {filteredPubs.map(pub => (
              <div
                key={pub.id}
                className="card card-hover"
                style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}
              >
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '0.5rem' }}>
                  <div style={{ display: 'flex', gap: '0.5rem' }}>
                    <span className="badge badge-teal">{pub.type}</span>
                    <span className="badge badge-navy">{pub.year}</span>
                  </div>
                  <span style={{ fontSize: '0.85rem', color: 'var(--text-light)', fontFamily: 'monospace' }}>
                    DOI: {pub.doi}
                  </span>
                </div>

                <h3 style={{ fontSize: '1.3rem', color: 'var(--primary-dark)' }}>
                  {getText(pub.title)}
                </h3>

                <div style={{ fontSize: '0.92rem', color: 'var(--accent-teal)', fontWeight: 600 }}>
                  ✍️ {pub.authors} — <em style={{ color: 'var(--primary-dark)' }}>{pub.journal}</em>
                </div>

                <p style={{ fontSize: '0.95rem', color: 'var(--text-muted)', lineHeight: 1.6 }}>
                  {getText(pub.abstract)}
                </p>

                {/* Keywords Tags */}
                <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap', marginTop: '0.25rem' }}>
                  {pub.keywords.map((kw, i) => (
                    <span key={i} style={{ fontSize: '0.78rem', backgroundColor: 'var(--bg-alt)', padding: '0.2rem 0.6rem', borderRadius: '4px', color: 'var(--text-muted)' }}>
                      #{kw}
                    </span>
                  ))}
                </div>

                <div style={{ display: 'flex', gap: '0.75rem', marginTop: '0.5rem' }}>
                  <button
                    onClick={() => setSelectedPub(pub)}
                    className="btn btn-navy btn-sm"
                  >
                    <BookOpen size={15} />
                    <span>{ui.viewPublication}</span>
                  </button>

                  {pub.externalUrl && (
                    <a
                      href={pub.externalUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="btn btn-outline btn-sm"
                    >
                      <ExternalLink size={15} />
                      <span>DOI Link</span>
                    </a>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Publication Detail Modal */}
      {selectedPub && (
        <div className="modal-overlay" onClick={() => setSelectedPub(null)}>
          <div className="modal-content" onClick={e => e.stopPropagation()} style={{ maxWidth: '750px' }}>
            <button
              onClick={() => setSelectedPub(null)}
              style={{
                position: 'absolute',
                top: '1.25rem',
                [isRtl ? 'left' : 'right']: '1.25rem',
                background: 'none',
                border: 'none',
                cursor: 'pointer'
              }}
            >
              <X size={24} color="var(--primary-dark)" />
            </button>

            <div style={{ display: 'flex', gap: '0.5rem', marginBottom: '1rem' }}>
              <span className="badge badge-teal">{selectedPub.type}</span>
              <span className="badge badge-navy">{selectedPub.year}</span>
            </div>

            <h2 style={{ fontSize: '1.45rem', marginBottom: '0.75rem', color: 'var(--primary-dark)' }}>
              {getText(selectedPub.title)}
            </h2>

            <div style={{ fontSize: '0.95rem', color: 'var(--accent-teal)', fontWeight: 700, marginBottom: '0.5rem' }}>
              {selectedPub.authors}
            </div>
            <div style={{ fontSize: '0.95rem', fontStyle: 'italic', marginBottom: '1.25rem', color: 'var(--primary-dark)' }}>
              Published in: {selectedPub.journal} ({selectedPub.year})
            </div>

            <div style={{ backgroundColor: 'var(--bg-alt)', padding: '1.25rem', borderRadius: 'var(--radius-md)', marginBottom: '1.5rem' }}>
              <h4 style={{ marginBottom: '0.5rem', color: 'var(--primary-dark)' }}>
                {isRtl ? 'الملخص الطبي (Abstract):' : 'Abstract:'}
              </h4>
              <p style={{ fontSize: '0.95rem', lineHeight: 1.7, color: 'var(--text-muted)' }}>
                {getText(selectedPub.abstract)}
              </p>
            </div>

            <div style={{ marginBottom: '1.5rem' }}>
              <h4 style={{ fontSize: '0.9rem', marginBottom: '0.4rem', color: 'var(--primary-dark)' }}>Keywords:</h4>
              <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
                {selectedPub.keywords.map((kw, idx) => (
                  <span key={idx} className="badge badge-navy" style={{ textTransform: 'none' }}>
                    {kw}
                  </span>
                ))}
              </div>
            </div>

            <div style={{ display: 'flex', gap: '1rem', flexWrap: 'wrap' }}>
              {selectedPub.externalUrl && (
                <a
                  href={selectedPub.externalUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn btn-primary btn-sm"
                >
                  <ExternalLink size={16} />
                  <span>{isRtl ? 'عرض الورقة بموقع المجلة' : 'Read Publisher Article'}</span>
                </a>
              )}
              <button
                onClick={() => setSelectedPub(null)}
                className="btn btn-outline btn-sm"
              >
                {ui.close}
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

// frontend/src/app/features/publications/publications.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { LanguageService } from '../../core/services/language.service';
import { DataService } from '../../core/services/data.service';
import { PublicationItem } from '../../core/models';

@Component({
  selector: 'app-publications',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div>
      <!-- Hero Header -->
      <section style="background-color: var(--primary-light); padding: 4rem 0;">
        <div className="container" style="text-align: center; max-width: 800px;">
          <span className="section-subtitle">{{ lang.isRtl() ? 'الأبحاث والمنشورات' : 'Peer-Reviewed Literature' }}</span>
          <h1 style="color: var(--primary-dark); margin-bottom: 1rem;">
            {{ lang.isRtl() ? 'المنشورات والأبحاث العلمية' : 'Publications & Research Output' }}
          </h1>
          <p style="font-size: 1.1rem; color: var(--text-muted);">
            {{ lang.isRtl() ? 'أبحاث سريرية محكمة في المجلات الطبية الدولية.' : 'Peer-reviewed research articles published in index-listed medical journals.' }}
          </p>
        </div>
      </section>

      <!-- Filter Controls Bar -->
      <section style="padding: 2rem 0; background-color: var(--bg-alt); border-bottom: 1px solid var(--border-light);">
        <div className="container">
          <div style="display: flex; gap: 1rem; flex-wrap: wrap; align-items: center;">
            <!-- Search Bar -->
            <div style="flex: 2 1 260px;">
              <input
                type="text"
                [(ngModel)]="searchTerm"
                className="input-field"
                [placeholder]="lang.isRtl() ? 'بحث في الأبحاث والكلمات المفتاحية...' : 'Search title, abstract, keywords...'"
              />
            </div>

            <!-- Year Filter -->
            <div style="flex: 1 1 180px;">
              <select [(ngModel)]="selectedYear" className="input-field">
                <option value="ALL">{{ lang.isRtl() ? 'جميع السنوات' : 'All Years' }}</option>
                <option *ngFor="let y of years" [value]="y">{{ y }}</option>
              </select>
            </div>

            <!-- Type Filter -->
            <div style="flex: 1 1 180px;">
              <select [(ngModel)]="selectedType" className="input-field">
                <option value="ALL">{{ lang.isRtl() ? 'جميع الأنواع' : 'All Types' }}</option>
                <option *ngFor="let t of types" [value]="t">{{ t }}</option>
              </select>
            </div>

            <!-- Clear Button -->
            <button
              *ngIf="searchTerm || selectedYear !== 'ALL' || selectedType !== 'ALL'"
              (click)="searchTerm = ''; selectedYear = 'ALL'; selectedType = 'ALL';"
              className="btn btn-outline btn-sm"
            >
              {{ lang.isRtl() ? 'مسح الفلاتر' : 'Clear Filters' }}
            </button>
          </div>
        </div>
      </section>

      <!-- Publications List -->
      <section className="section" style="padding-top: 2rem;">
        <div className="container">
          <div style="font-size: 0.9rem; color: var(--text-muted); margin-bottom: 1.5rem;">
            {{ lang.isRtl() ? 'تم العثور على ' + getFilteredPubs().length + ' بحث علمي' : 'Showing ' + getFilteredPubs().length + ' research publications' }}
          </div>

          <div style="display: flex; flex-direction: column; gap: 1.5rem;">
            <div
              *ngFor="let pub of getFilteredPubs()"
              className="card card-hover"
              style="display: flex; flex-direction: column; gap: 0.75rem;"
            >
              <div style="display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 0.5rem;">
                <div style="display: flex; gap: 0.5rem;">
                  <span className="badge badge-teal">{{ pub.type }}</span>
                  <span className="badge badge-navy">{{ pub.year }}</span>
                </div>
                <span style="font-size: 0.85rem; color: var(--text-light); font-family: monospace;">
                  DOI: {{ pub.doi }}
                </span>
              </div>

              <h3 style="font-size: 1.3rem; color: var(--primary-dark);">
                {{ lang.getText(pub.title) }}
              </h3>

              <div style="font-size: 0.92rem; color: var(--accent-teal); font-weight: 600;">
                ✍️ {{ pub.authors }} — <em style="color: var(--primary-dark);">{{ pub.journal }}</em>
              </div>

              <p style="font-size: 0.95rem; color: var(--text-muted); line-height: 1.6;">
                {{ lang.getText(pub.abstract) }}
              </p>

              <!-- Keywords Tags -->
              <div style="display: flex; gap: 0.5rem; flex-wrap: wrap; margin-top: 0.25rem;">
                <span *ngFor="let kw of pub.keywords" style="font-size: 0.78rem; background-color: var(--bg-alt); padding: 0.2rem 0.6rem; border-radius: 4px; color: var(--text-muted);">
                  #{{ kw }}
                </span>
              </div>

              <div style="display: flex; gap: 0.75rem; margin-top: 0.5rem;">
                <button (click)="selectedPub = pub" className="btn btn-navy btn-sm">
                  <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 19.5v-15A2.5 2.5 0 0 1 6.5 2H20v20H6.5a2.5 2.5 0 0 1-2.5-2.5Z"/><path d="M6 6h10"/><path d="M6 10h10"/></svg>
                  <span>{{ lang.isRtl() ? 'عرض البحث' : 'View Publication' }}</span>
                </button>

                <a *ngIf="pub.pdfUrl" [href]="pub.pdfUrl" target="_blank" rel="noopener noreferrer" className="btn btn-outline btn-sm">
                  <svg xmlns="http://www.w3.org/2000/svg" width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" x2="21" y1="14" y2="3"/></svg>
                  <span>DOI Link</span>
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- Publication Detail Modal -->
      <div *ngIf="selectedPub" className="modal-overlay" (click)="selectedPub = null">
        <div className="modal-content" (click)="$event.stopPropagation()" style="max-width: 750px;">
          <button (click)="selectedPub = null" style="position: absolute; top: 1.25rem; background: none; border: none; cursor: pointer;" [style.left]="lang.isRtl() ? '1.25rem' : 'auto'" [style.right]="lang.isRtl() ? 'auto' : '1.25rem'">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--primary-dark)" stroke-width="2"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>
          </button>

          <div style="display: flex; gap: 0.5rem; margin-bottom: 1rem;">
            <span className="badge badge-teal">{{ selectedPub.type }}</span>
            <span className="badge badge-navy">{{ selectedPub.year }}</span>
          </div>

          <h2 style="font-size: 1.45rem; margin-bottom: 0.75rem; color: var(--primary-dark);">
            {{ lang.getText(selectedPub.title) }}
          </h2>

          <div style="font-size: 0.95rem; color: var(--accent-teal); font-weight: 700; margin-bottom: 0.5rem;">
            {{ selectedPub.authors }}
          </div>
          <div style="font-size: 0.95rem; font-style: italic; margin-bottom: 1.25rem; color: var(--primary-dark);">
            Published in: {{ selectedPub.journal }} ({{ selectedPub.year }})
          </div>

          <div style="background-color: var(--bg-alt); padding: 1.25rem; border-radius: var(--radius-md); margin-bottom: 1.5rem;">
            <h4 style="margin-bottom: 0.5rem; color: var(--primary-dark);">
              {{ lang.isRtl() ? 'الملخص الطبي (Abstract):' : 'Abstract:' }}
            </h4>
            <p style="font-size: 0.95rem; line-height: 1.7; color: var(--text-muted);">
              {{ lang.getText(selectedPub.abstract) }}
            </p>
          </div>

          <div style="margin-bottom: 1.5rem;">
            <h4 style="font-size: 0.9rem; margin-bottom: 0.4rem; color: var(--primary-dark);">Keywords:</h4>
            <div style="display: flex; gap: 0.5rem; flex-wrap: wrap;">
              <span *ngFor="let kw of selectedPub.keywords" className="badge badge-navy">
                {{ kw }}
              </span>
            </div>
          </div>

          <div style="display: flex; gap: 1rem; flex-wrap: wrap;">
            <a *ngIf="selectedPub.pdfUrl" [href]="selectedPub.pdfUrl" target="_blank" rel="noopener noreferrer" className="btn btn-primary btn-sm">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" x2="21" y1="14" y2="3"/></svg>
              <span>{{ lang.isRtl() ? 'عرض الورقة بموقع المجلة' : 'Read Publisher Article' }}</span>
            </a>
            <button (click)="selectedPub = null" className="btn btn-outline btn-sm">
              {{ lang.isRtl() ? 'إغلاق' : 'Close' }}
            </button>
          </div>
        </div>
      </div>
    </div>
  `
})
export class PublicationsComponent {
  lang = inject(LanguageService);
  data = inject(DataService);

  searchTerm = '';
  selectedYear = 'ALL';
  selectedType = 'ALL';
  selectedPub: PublicationItem | null = null;

  years = [2023, 2022, 2021, 2020];
  types = ['Original Research', 'Review Article', 'Clinical Study', 'Case Report'];

  getFilteredPubs(): PublicationItem[] {
    return this.data.getPublications().filter(pub => {
      const matchesSearch = !this.searchTerm ||
        this.lang.getText(pub.title).toLowerCase().includes(this.searchTerm.toLowerCase()) ||
        this.lang.getText(pub.abstract).toLowerCase().includes(this.searchTerm.toLowerCase()) ||
        pub.keywords.some(k => k.toLowerCase().includes(this.searchTerm.toLowerCase()));

      const matchesYear = this.selectedYear === 'ALL' || pub.year.toString() === this.selectedYear;
      const matchesType = this.selectedType === 'ALL' || pub.type === this.selectedType;

      return matchesSearch && matchesYear && matchesType;
    });
  }
}
